#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'code_challenge'

sample = File.new('sample_multiple.txt')

CodeChallenge.new(sample).validate_boards

# values = []
# while a = gets
#   values << a.split(/\s/).map(&:to_i)
# end

# item = Sudoku.new(values)
